title: "Chuck Sylvester"
description: "AI/ML Software Engineer"
theme: minima

header_pages:
  - index.md
  - about.md
  - med-insight.md

collections:
  med-insight:
    output: true
    permalink: /med-insight/:name/

# Optional: add your GitHub, LinkedIn, etc. later
