title: "Chuck Sylvester"
description: "AI/ML Software Engineer"
# theme: minima
theme: jekyll-theme-slate

header_pages:
  - about.md
  - blog.md
  - portfolio.md

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Optional: add your GitHub, LinkedIn, etc. later
