title: "Chuck Sylvester"
description: "AI/ML Software Engineer"
theme: minima

sass:
  sass_dir: assets/css

header_pages:
  - about.md
  - blog.md
  - portfolio.md

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Optional: add your GitHub, LinkedIn, etc. later
